import type { DocsHref } from "@/lib/docs/components";

/**
 * DocSection titles per docs page. Keep in sync with `<DocSection title>` on
 * that page — used so changelog `section` stays typed. DocSection reads
 * badges from `updates` automatically.
 */
export const DOC_SECTIONS = {
  "/docs/accordion": [
    "Playground",
    "Standalone",
    "Single Expand",
    "Multi Expand",
    "Row highlight",
    "API Reference — Accordion / AccordionGroup",
    "API Reference — AccordionItem",
    "API Reference — AccordionTrigger",
    "API Reference — AccordionContent",
  ],
  "/docs/ask-user-questions": [
    "Playground",
    "Multiple questions",
    "Multi-select",
    "With other",
    "Free text",
    "Free text validation",
    "Skippable",
    "Chip on left",
    "Stacked layout",
    "Controlled",
    "API Reference — AskUserQuestions",
    "API Reference — AskUserQuestion",
    "API Reference — AskUserOption",
    "API Reference — AskUserAnswer",
  ],
  "/docs/badge": ["Solid", "Dot", "Colors", "API Reference"],
  "/docs/banner": [
    "Playground",
    "Statuses",
    "Actions",
    "Fixed",
    "Custom icon",
    "API Reference: Banner",
    "API Reference: Parts",
    "API Reference: BannerAction",
  ],
  "/docs/button": [
    "Playground",
    "Variants",
    "With Icons",
    "Loading & Disabled",
    "API Reference",
  ],
  "/docs/card": [
    "Playground",
    "Basic",
    "Grid: 2-D fluid hover",
    "Outlined group",
    "Separated tiles",
    "Fully yours — compose anything",
    "Selected",
    "API Reference — Card",
    "API Reference — CardGroup",
    "API Reference — Parts",
    "API Reference — CardButton",
  ],
  "/docs/carousel-dots": ["Static", "Autoplay", "API Reference"],
  "/docs/chat-message": [
    "Conversation",
    "Roles",
    "Attachments",
    "API Reference",
  ],
  "/docs/checkbox-group": [
    "Basic",
    "API Reference — CheckboxGroup",
    "API Reference — CheckboxItem",
  ],
  "/docs/color-picker": [
    "Default",
    "Popover",
    "With Swatches",
    "OKLCH Format",
    "Controlled",
    "Removable Trigger",
    "Eyedropper Support",
    "ColorPicker Props",
    "ColorPickerPopover Props",
  ],
  "/docs/combobox": [
    "Playground",
    "Basic",
    "With icons",
    "Multiple selection",
    "Create from the query",
    "Hide picked rows",
    "Variants",
    "Long list",
    "Error & disabled",
    "API Reference — Combobox",
    "API Reference — ComboboxInput",
    "API Reference — ComboboxChips",
    "API Reference — ComboboxContent",
    "API Reference — ComboboxList",
    "API Reference — ComboboxItem",
    "API Reference — ComboboxEmpty",
  ],
  "/docs/command-menu": [
    "Playground",
    "Basic",
    "Descriptions, shortcuts, disabled rows",
    "Suggestions",
    "Tabs",
    "Filters",
    "Dialog and trigger shortcut",
    "Footer hints",
    "Custom rows",
    "API Reference: Item data",
    "API Reference: CommandMenu",
    "API Reference: CommandMenuDialog",
    "API Reference: CommandMenuInput",
    "API Reference: CommandMenuTabs",
    "API Reference: CommandMenuList",
    "API Reference: CommandMenuItem",
    "API Reference: CommandMenuFooter",
    "API Reference: CommandMenuShortcut",
  ],
  "/docs/dialog": [
    "Basic",
    "Sizes",
    "With a sidebar",
    "API Reference — Dialog",
    "API Reference — DialogTrigger / DialogClose",
    "API Reference — DialogContent",
  ],
  "/docs/dropdown": [
    "Playground",
    "Basic",
    "Groups",
    "Triggered menu",
    "Submenus",
    "Multiple selection",
    "Searchable menu",
    "Searchable multiple selection",
    "Create from the query",
    "API Reference — Dropdown",
    "API Reference — MenuItem",
    "API Reference — DropdownMenu",
    "API Reference — DropdownTrigger",
    "API Reference — DropdownContent",
    "API Reference — DropdownSub",
    "API Reference — DropdownSubTrigger",
    "API Reference — DropdownSubContent",
    "API Reference — DropdownSearch",
    "API Reference — DropdownEmpty",
    "API Reference — DropdownLabel",
    "API Reference — DropdownSeparator",
  ],
  "/docs/fluid-hover": [
    "Blink or glide",
    "Show the math",
    "3 axes",
    "When to split a list",
    "What it costs",
    "Reduced motion",
    "Reference",
  ],
  "/docs/input-copy": [
    "Basic",
    "With Label",
    "Button Variant",
    "Left Aligned",
    "Disabled",
    "Copy Callback",
    "API Reference",
  ],
  "/docs/input-group": [
    "Basic",
    "Multiple Fields",
    "Error State",
    "API Reference — InputGroup",
    "API Reference — InputField",
  ],
  "/docs/input-message": [
    "Playground",
    "Basic",
    "Suggestions",
    "Attachments",
    "Queued messages",
    "Left Slot Only",
    "Right Slot Only",
    "Send Handler",
    "Disabled",
    "API Reference",
  ],
  "/docs/motion": ["Three speeds", "Slow in, faster out", "All tokens"],
  "/docs/radio-group": [
    "Basic",
    "API Reference — RadioGroup",
    "API Reference — RadioItem",
  ],
  "/docs/scrollbars": [
    "The problem",
    "The scrollbar",
    "The fade",
    "Examples",
    "API reference",
  ],
  "/docs/select": [
    "Basic",
    "Variants",
    "With Icons",
    "Groups",
    "Scrollable List",
    "Error State",
    "Disabled",
    "API Reference — Select",
    "API Reference — SelectTrigger",
    "API Reference — SelectContent",
    "API Reference — SelectItem",
  ],
  "/docs/sidebar": [
    "Playground",
    "Layouts",
    "Nesting",
    "Actions & badges",
    "Header & footer",
    "Callouts",
    "Resize, collapse & peek",
    "Inside a dialog",
    "No icon rail version?",
    "Functional and perfectly aligned",
    "API Reference — SidebarProvider",
    "API Reference — Sidebar",
    "API Reference — Sections",
    "API Reference — Content level 1",
    "API Reference — Content level 2",
  ],
  "/docs/sizes": [
    "The principle",
    "Typography scale",
    "Compact regions",
    "Token reference",
    "SizeProvider props",
    "Component size prop",
  ],
  "/docs/skill": ["What it does", "What it knows", "Examples"],
  "/docs/slider": [
    "Compact",
    "Range",
    "Steps",
    "Non-uniform Steps",
    "Value Display",
    "Format",
    "Disabled",
    "Default",
    "Default — Scrubber",
    "Default — Format",
    "Default — Disabled",
    "API Reference",
  ],
  "/docs/surfaces": ["The problem", "The solution", "Examples"],
  "/docs/switch": ["Basic", "Disabled", "API Reference"],
  "/docs/table": [
    "Basic",
    "API Reference — Table",
    "API Reference — TableRow",
  ],
  "/docs/tabs": [
    "Basic",
    "With Icons",
    "Controlled",
    "API Reference — Tabs",
    "API Reference — TabsList",
    "API Reference — TabItem",
    "API Reference — TabPanel",
  ],
  "/docs/tabs-subtle": [
    "Basic",
    "With Icons",
    "Active Label",
    "API Reference — TabsSubtle",
    "API Reference — TabsSubtleItem",
    "API Reference — TabsSubtlePanel",
  ],
  "/docs/thinking-indicator": ["Basic", "API Reference"],
  "/docs/thinking-steps": [
    "Basic",
    "Minimal",
    "Streaming",
    "Streaming Text",
    "With Images",
    "Full Example",
    "API Reference",
  ],
  "/docs/tooltip": [
    "Basic",
    "Placement",
    "Rich Content",
    "Follow cursor",
    "Delay",
    "API Reference",
  ],
  "/docs/typography": [
    "5 rules",
    "5 no-gos",
    "The scale",
    "Markdown",
    "Spacing",
    "5 tweaks",
  ],
} as const satisfies {
  [H in DocsHref]?: readonly string[];
};

export type DocSectionsMap = typeof DOC_SECTIONS;

/** Docs pages that have a registered section list. */
export type SectionedDocsHref = keyof DocSectionsMap;

/** Section title allowed for a docs href (never if the page isn't registered). */
export type DocSectionTitle<H extends DocsHref> = H extends SectionedDocsHref
  ? DocSectionsMap[H][number]
  : never;
